/*
 * ACTION TYPES
 */
export const TAKE_PICTURE = 'TAKE_PICTURE';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const START_IMAGE_UPLOAD = 'START_IMAGE_UPLOAD';
export const IMAGE_UPLOAD_COMPLETE = 'IMAGE_UPLOAD_COMPLETE';
